# Calendars configuration
[[calendars]]
name = "Personal"
path = "~/.local/share/vdirsyncer/calendar/personal"
color = "blue" # TODO: implement colors
default = true

[[calendars]]
name= "Work"
path = "~/.local/share/vdirsyncer/calendar/work"
color = "green"
default = false

# UI configuration
[ui]
window_name = "Todos"
show_footer_keybindings = true
select_first = true
rounded_borders = true
date_format = "%m/%d/%y %H:%M:%S"

