# Calendars configuration
[Calendars]
[Calendars.personal]
path = "~/.local/share/vdirsyncer/calendar/personal"
color = "blue"
default = true

[Calendars.work]
path = "~/some/other/path/work"
color = "green"
default = false

# UI configuration
[UI]
window_name = "Todos"
show_footer_keybindings = true
select_first = true
rounded_borders = true
date_format = "%m/%d/%y %H:%M:%S"

