[project]
name = "cursedtodo"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "François Lachèse", email = "francois.lachese@gmail.com"},
]
dependencies = [
    "ics>=0.7.2",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[project.scripts]
ctodo = "cursedtodo.cursedtodo:main"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
