[[calendars]]
name= "Default"
path = "~/.local/share/cursedtodos/calendar/default" # should be something like ~/.local/share/vdirsyncer/calendar/work if you are using vdirsyncer
color = "green"
default = false

# UI configuration
[ui]
window_name = "Todos"
show_footer_keybindings = true
select_first = true
rounded_borders = true
date_format = "%m/%d/%y %H:%M:%S"
category_colors = true
confirm_mark_as_done = true

# Columns configuration
[[columns]]
property = "calendar.name"
width = 10

[[columns]]
property = "summary"
width = 30

[[columns]]
property = "priority"
width = 15

[[columns]]
property = "due"
width = 25

[[columns]]
property = "categories"
width = 30
