name: Release
on: workflow_dispatch

jobs:
  pypi-publish:
    name: create demo.gif
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4

      - name: install dependencies
        run: sudo apt-get install -y asciinema expect


      - name: Publish package distributions to PyPI
        run: ../../demo.sh
      - uses: actions/upload-artifact@v4
        with:
          name: demo
          path: ./demo.gif
