name: Pull Request CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true

      - name: Install dependencies
        run: | 
          python --version
          pdm install --frozen-lockfile

      - name: Run Ruff
        run: pdm run ruff check

      - name: Run MyPy
        run: pdm run mypy --python-version=${{ matrix.python-version }} src

