name: Pull request
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - name: install
        run: pdm install
      - name: ruff
        run: |
          pdm run ruff check
      - name: mypy
        run: |
          pdm run mypy src



